# Generated by Django 5.1.3 on 2024-11-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='p_image',
            field=models.ImageField(upload_to='project_images'),
        ),
    ]
